### ISSUE TITLE
[OSPO Book]: many broken links to todogroup.org.

### ISSUE THREAD

**Issue by jfg956** [todogroup/ospology#395]
Hi, there are many broken links to the TODO Group Website in the OSPO Book.  Some examples in {1}, {2} and {3}.

{1}: https://github.com/todogroup/ospology/blob/b53f3dd405b2be91458d029411bca2012c53b4c7/ospo-book/content/en/03-chapter.md?plain=1#L63

{2}: https://github.com/todogroup/ospology/blob/b53f3dd405b2be91458d029411bca2012c53b4c7/ospo-book/content/en/03-chapter.md?plain=1#L84

{3}: https://github.com/todogroup/ospology/blob/b53f3dd405b2be91458d029411bca2012c53b4c7/ospo-book/content/en/references.md?plain=1#L30C50-L30C94

I suspect most of the urls to not be working, I tested a few in below.

```
$ grep -r todogroup.*guides ospo-book/ | sed -e 's/.*http/http/;s/[ \)|].*//' | sort | uniq -c
   2 https://todogroup.org/guides/building-leadership/         <<<===--- this does not work.
   2 https://todogroup.org/guides/casestudies/autodesk/        <<<===--- this works.
   2 https://todogroup.org/guides/casestudies/capitalone/      <<<===--- this does not work.
   2 https://todogroup.org/guides/casestudies/comcast/         <<<===--- this works.
   2 https://todogroup.org/guides/casestudies/dropbox/
   2 https://todogroup.org/guides/casestudies/facebook/
   2 https://todogroup.org/guides/casestudies/microsoft/
   2 https://todogroup.org/guides/casestudies/ni/
   4 https://todogroup.org/guides/casestudies/porsche/
   2 https://todogroup.org/guides/casestudies/redhat/
   2 https://todogroup.org/guides/casestudies/salesforce/
   2 https://todogroup.org/guides/casestudies/sap/
   2 https://todogroup.org/guides/casestudies/uber/
   2 https://todogroup.org/guides/create-program/           <<<===--- this does not work.
   2 https://todogroup.org/guides/diversity-inclusion/      <<<===--- this does not work.
   2 https://todogroup.org/guides/improve-your-open-source-development-impact/     <<<===--- this works.
   2 https://todogroup.org/guides/management-tools/         <<<===--- this does not work.
   2 https://todogroup.org/guides/managing-career-development-within-ospo/
   2 https://todogroup.org/guides/marketing-open-source-projects/
   2 https://todogroup.org/guides/measuring/
   2 https://todogroup.org/guides/organizing-and-managing-open-source-events/
   2 https://todogroup.org/guides/os-commercial-ecosystem/
   6 https://todogroup.org/guides/outbound-oss/
   4 https://todogroup.org/guides/participating/
   2 https://todogroup.org/guides/recruiting-open-source-developers/
   2 https://todogroup.org/guides/shutting-down-an-open-source-project/
   2 https://todogroup.org/guides/starting-an-open-source-project/
   6 https://todogroup.org/guides/strategy/
   2 https://todogroup.org/guides/using-open-source/
```

With a little work, it is possible to find the right page by editing the URL and looking in {4} or {5}.

{4}: https://todogroup.org/resources/guides/

{5}: https://todogroup.org/resources/case-studies/

Sorry, I do not have time to provide a PR, and maybe this should be addressed by a redirect on the TODO Group Website, not by an edit of the OSPO Book (or by both).

Thanks for looking into this,

Jean-François Gagné

**Comment by node** [comment]
Thanks for your feedback, I will try to fix most of them.

**Comment by node** [comment]
Track list:

- [ ] 03-chapter.md
- [ ] references.md

**Comment by node** [comment]
Hi @jfg956 this issue has been fixed now, cloud you please check it or give us some feedback ? We hope output better experience for all .

**Comment by jfg956** [comment]
Thanks Chris.  You commit looks good, but I still get broken links in {1}, examples:
* document this strategy in an open source strategy document --> 404
* identify the open source projects and communities with which you will work --> 404

{1}: https://ospobook.todogroup.org/03-chapter/

Was your changes deployed ?

**Comment by anajsana** [comment]
Cc'ing @cjyabraham. Any thoughts about why the deployment for the #396 PR was not made when merging? 🤔

**Comment by cjyabraham** [comment]
It appears that the netlify deployment thought there were no changes and so cancelled the deployment. Obviously this wasn't correct but I'm not sure why it made this error. I have manually triggered the deployment now so the changes should now be live.

**Comment by jfg956** [comment]
Thanks Chris Y., Ana and Chris A., things look good, closing.
